apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      values: |
        clusterName: es-cluster
        nodeGroup: data
        replicas: 1
        resources:
          requests:
            memory: "1Gi"
        volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              storageClassName: "local-path"
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
