apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/joshuamcbeth/talos-argocd.git'
    targetRevision: HEAD
    path: infrastructure/elastic-system
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
