apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-porkbun
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/joshuamcbeth/talos-argocd.git
    targetRevision: HEAD
    path: manifests/external-dns

  destination:
    server: https://kubernetes.default.svc
    namespace: dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Allows ArgoCD to process a single file containing multiple resources
      - ServerSideApply=true
