apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/joshuamcbeth/talos-argocd.git'
      targetRevision: HEAD
      path: infrastructure/fluent-bit
      name: config-crds

    - repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.54.0
      chart: fluent-bit
      helm:
        values: |
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
          envFrom:
            - secretRef:
                name: elasticsearch-user-auth
          config:
            filters: |
              [FILTER]
                  Name modify
                  Match kube.*
                  Rename kubernetes.labels.app kubernetes.labels.app_name
            outputs: |
              [OUTPUT]
                  Name es
                  Match kube.*
                  Host elasticsearch-master.elastic-system.svc.cluster.local
                  Logstash_Format On
                  Retry_Limit False
                  TLS On
                  TLS.Verify Off
                  HTTP_User ${USERNAME}
                  HTTP_Passwd ${PASSWORD}
                  Suppress_Type_Name On
              [OUTPUT]
                  Name es
                  Match host.*
                  Host elasticsearch-master.elastic-system.svc.cluster.local
                  Logstash_Format On
                  Logstash_Prefix node
                  Retry_Limit False
                  TLS On
                  TLS.Verify Off
                  HTTP_User ${USERNAME}
                  HTTP_Passwd ${PASSWORD}
                  Suppress_Type_Name On

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
