apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/joshuamcbeth/talos-argocd.git'
      targetRevision: HEAD
      path: infrastructure/harbor
      name: config



    - repoURL: https://helm.goharbor.io
      targetRevision: 1.18.0
      chart: harbor
      helm:
        values: |
          expose:
            type: ingress
            tls:
              enabled: true
              certSource: secret
              secret:
                secretName: harbor-tls-secret
            ingress:
              className: "nginx"
              hosts:
                core: harbor.kubernetes.name
              annotations:
                external-dns.alpha.kubernetes.io/hostname: harbor.kubernetes.name
          externalURL: https://harbor.kubernetes.name
          persistence:
            persistentVolumeClaim:
              registry:
                storageClass: "local-path"
                size: 10Gi
              jobservice:
                jobLog:
                  storageClass: "local-path"
                  size: 1Gi
              database:
                storageClass: "local-path"
                size: 1Gi
              redis:
                storageClass: "local-path"
                size: 1Gi
              trivy:
                storageClass: "local-path"
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - WaitForChildResources=true
