apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  project: default
  sources:
    - repoURL: 'https://github.com/joshuamcbeth/talos-argocd.git'
      targetRevision: HEAD
      path: infrastructure/istio
      name: config

    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.28.x
      chart: base
      helm:
        parameters:
        - name: defaultRevision
          value: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
    - /webhooks/0/failurePolicy
