apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-core
  namespace: argocd
  labels:
    name: keda
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.18.1

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
