apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: kibana
    helm:
      values: |
        elasticsearchHosts: elasticsearch-master.elastic-system.svc.cluster.local
        service:
          type: LoadBalancer

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    dependsOn:
    - name: elasticsearch
      namespace: argocd
