apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: kibana
    helm:
      values: |
        extraEnvs:
          - name: "NODE_TLS_REJECT_UNAUTHORIZED"
            value: "0"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
        elasticsearchHosts: https://elasticsearch-master.elastic-system.svc:9200
        service:
          type: LoadBalancer

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
