apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-porkbun
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joshua.mcbeth@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - selector:
        dnsZones:
          - kubernetes.name
      dns01:
        webhook:
          groupName: porkbun.acme.solver
          solverName: porkbun
          config:
            apiKeySecretRef:
              name: porkbun-cert-manager-secret
              key: api-key
            secretKeySecretRef:
              name: porkbun-cert-manager-secret
              key: secret-key
