apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-porkbun
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joshua.mcbeth@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: porkbun.acme.solver
          solverName: porkbun-solver
