apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-certificate
  namespace: harbor
spec:
  secretName: harbor-tls-secret
  dnsNames:
  - harbor.kubernetes.name
  issuerRef:
    name: letsencrypt-porkbun
    kind: ClusterIssuer
  usages:
  - server auth
